export enum HandlerName {
  INTERNAL_TEST_1 = 'INTERNAL_TEST_1',
  INTERNAL_TEST_2 = 'INTERNAL_TEST_2',
  INTERNAL_HEALTH_CHECK = 'INTERNAL_HEALTH_CHECK',
  MARKED_DATA_CALCULATE = 'MARKED_DATA_CALCULATE',
}
